### ISSUE TITLE
Websocket client connection (feature request)

### ISSUE THREAD

**Issue by jimmyt857** [alexhultman/uWebSockets#104]
I see that your README explicitly states this library is intended as a server, but would it be possible to include a client implementation as well?

**Comment by alexhultman** [comment]
Personally I don't see any use for a client library? The browser is supposed to be the client as far as I understand, and even if you absolutely need a client there is no need to write yet another library as there already exists decent alternatives like WebSocket++ (this library is pretty damn efficient). WebSocket++ is terrible as the server since it consumes all memory in the universe, but works good as a client where you only need one, maybe two connections. That is how I see it at least, correct me if I'm wrong.

**Comment by SEAPUNK** [comment]
The browser is not the only client that you can have: You can have mobile app clients, server clients, etc.

I'd personally like to see a client counterpart to uWebsockets is pretty much for the reason of not having to install two separate packages, and being able to create clients with the existing uWebsockets' already highly efficient code base (parser, and etc.), because even though there usually won't be more than one/two connections at a time, there will definitely be connections with very high throughput that require a focus on performance, like [uWebsockets provides](https://i.imgur.com/QFxpQ71.png).

**Comment by LordMajestros** [comment]
Socket.io has many client libraries(android,iOS,etc).
Socket.io now has support for uWebSockets in engine.io (https://github.com/kapouer/engine.io)
So you can consider using that for now.

**Comment by SEAPUNK** [comment]
Note that `engine.io` is the server and `engine.io-client` is the client.

**Comment by LordMajestros** [comment]
Yes and `engine.o-client` will work with `engine.io` same way `socket.o-client` will work with socket.io using uwebsockets as the websocket library in engine.io. The point is the old engine.io supported only ws as the websocket library on the server and now supports uWebsockets as well.

**Comment by lpinca** [comment]
You can use the current `engine.io-client` with `engine.io` + `uws`, the same should also be valid for Socket.IO.

**Comment by SEAPUNK** [comment]
Yes, but I'm not using socket.io: I'm using usually either plain websockets, or my own websocket framework that I'm working on. My point is not having to use two different implementations, `ws` and `uws` to be the client and the server, respectively.

**Comment by lpinca** [comment]
@SEAPUNK yes it may have sense, my comment was a response to @LordMajestros comment.

**Comment by LordMajestros** [comment]
WS(https://github.com/websockets/ws) is used in the tests for `engine.io` + `uws` and currently passes all tests so they should work very well together

**Comment by lpinca** [comment]
I actually think I have misread so ignore me :)

**Comment by LordMajestros** [comment]
Guessed as much 👍

**Comment by alexhultman** [comment]
@SEAPUNK Is socketeer faster than ws, as client?

**Comment by SEAPUNK** [comment]
@alexhultman Oh, no, it's just a framework that wraps around `ws`, a bit like socket.io is. I just build on top of websockets to make some functions easier.

But it's an example: I'd want to use `uws` in some later version, but if `uws` only provides the server, I'd have to keep `ws` or another package that provides a WebSocket client alongside of `uws` so I'd have both a server and a client.

**Comment by alexhultman** [comment]
I'm not planning to create a client library. I'm closing this, I need to finish the server first of all. Then depending on how much time I will have I can see what to do about this.

**Comment by jimmyt857** [comment]
I understand. This is an important feature to me, so with your permission I would like to submit a pull request for this. I imagine I can get to it in the next 1-2 weeks.

**Comment by alexhultman** [comment]
@jimmyt857 Sure, if you have anything that works I can take a look but you need to figure out how to modify the parser so that it works for server frames as well as client frames (currently the parser is optimized for receiving client frames only, they have 4 byte mask and masked messages).

Sending is easy, the tricky part is parsing the servers frames. I would start with this part. And I would just start by copying the current parser a la "koppy pasta" and change it. Parsing frames from the server will be easier than parsing frames from clients so you should end up with a simpler parser.

You see the flow - you get an event, you recv the data, you run the parser, you emit fragments, you append the fragments to the buffer, you emit the message event.

**Comment by jimmyt857** [comment]
Would you prefer to have separate parsers? I don't think it will be very difficult to use the same one, since the only difference is the masking.

**Comment by alexhultman** [comment]
I think the best is to just copy the code, duplicate everything and make a separate library for clients. Then we can see what is common and merge it in.

**Comment by jimmyt857** [comment]
Ok, sounds good. I'll let you know when I've got something working.

**Comment by alexhultman** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

These are very useful IMO

**Comment by alexhultman** [comment]
OMG, never mind that one was about using the browsers implementation, rofl!

**Comment by jimmyt857** [comment]
Haha thanks for the thought. Don't worry, I actually wrote a simple personal websockets library for myself in C# awhile ago so I have a pretty good handle on the protocol.

I guess I should mention though, I'm currently only planning to write a pull request for the C++ version of your project, and w/o wss or permessage-deflate.

**Comment by jimmyt857** [comment]
I've finished my first draft of the code for this, but I am having trouble with some libuv functions because I still don't fully understand them. My basic procedure is the following:

- Create a new tcp connection using the uv_tcp_t and uv_connect_t objects
- In the connect callback, send off the first message using uv_write
- In the write callback, create uv_poll_t around the same socket and wait for http response

However, I get seg faults from within libuv (in uv_poll_start), so I think something is wrong with the way I create the uv_poll_t handle. I'm using the same uv_poll_init_socket call that the server uses, is there anything I am missing?

**Comment by alexhultman** [comment]
You need to use Unix syscalls directly except for uv_poll_t which wraps the epolling. Uv_tcp_t is wah too heavyweight.

**Comment by jimmyt857** [comment]
Hmmm, but the regular connect() call is blocking, wouldn't that go against the point of this library?

**Comment by jimmyt857** [comment]
Wait, nevermind, I see you can set it to non-blocking mode, and I could have libuv wait on it for me Thanks. ;)

**Comment by jcelerier** [comment]
any updates on this ? it's cumbersome to have websocket++ for the client part and uWS for the server.
