### ISSUE TITLE
Benchmarks on the readme

### ISSUE THREAD

**Issue by ronkorving** [alexhultman/uWebSockets#112]
I think with recent changes, the benchmark data in the readme is a bit out of date. Perhaps it would be good to re-publish them on every release. In any case, could they be updated?

**Comment by alexhultman** [comment]
These benchmarks are still very valid. They are about 58 million times more valid than the ancient bullshit blog post that is the foundation of camp ws's superlative reservoir.

**Comment by alexhultman** [comment]
http://web.archive.org/web/20130314230536/http://hobbycoding.posterous.com/the-fastest-websocket-module-for-nodejs

This blog post is what ws links to. It is literally 5 years old and full of 100% bullshit. My benchmarks are top 2 months old and the results are pretty much identical still.

**Comment by ronkorving** [comment]
I'm not talking about ws, only about uWebSockets :) I wrote this issue because I believe it was you who recently said that with the change to always depending on Node's HTTP server, the memory usage would go up a lot. I'm wondering by how much.

**Comment by alexhultman** [comment]
These benchmarks are not for the Node.js addon but for the native library. The Node.js addon adds a ton of overhead and is currently about 10x more lightweight than ws if you use the ws interface, and should be about 15x - 20x faster. Connection performance is about 4x faster since the Node.js HTTP server is terribly slow. So yeah - using Node.js cripples performance a ton but it is a lot better than ws at least.

**Comment by alexhultman** [comment]
Maybe that is not overly true - if you use the addon straight up without any ws wrapper you should get pretty close to native memroy scaling and perf, not the connection perf though.
