### ISSUE TITLE
Information on thread safety?

### ISSUE THREAD

**Issue by ryanmjacobs** [alexhultman/uWebSockets#122]
Hi, thank you for creating this amazing library. I am seriously considering switching from WebSocket++ to μWebSockets, but my application depends heavily on thread safety.

For example, is it possible to store `Socket` objects outside of a thread, and have a separate thread call `socket.send()`? Would this hamper performance?

**Comment by alexhultman** [comment]
Hey,

Send is currently always thread unsafe, but I can see the use for a thread safe variant. I will take a look at this and see how it can be added. Of course you always have the uv_async_t to queue up work for a specific loop from other threads, but I think one could skip that step if the kernel buffer is not currently full.

**Comment by alexhultman** [comment]
Currently send works like this:

send(lalalala)
* is the kernel buffer not full? write directly to it.
* did we fit? return if so
* otherwise, start a poll for writable event to write the rest

The third step would probably have to be fixed for thread safety, but as you see most of send can actually be left with 0 perf loss (well it depends on if you want to lock the kernel buffer or not so give or take a mutex lock there also - but these are super lightweight when already unlocked :)

**Comment by ryanmjacobs** [comment]
Okay, thanks for the info. I really appreciate the quick response.
