### ISSUE TITLE
Difference between websocket spec and autobahn tests?

### ISSUE THREAD

**Issue by jimmyt857** [alexhultman/uWebSockets#151]
I'm starting to test my client with the autobahn tests. The very first test fails because when we echo a close frame, the close code is copied. The autobahn test says that it expects empty payload or code 1000 (Normal closure) in this case. However, the websocket spec says that endpoints typically echo the close code in an echoed close frame, as you have it (https://tools.ietf.org/html/rfc6455#section-5.5.1).

Just wanted to let you know about this. For now I'll make this change in my client branch.

**Comment by alexhultman** [comment]
You should aim for passing the Autobahn. Many implementations rely on their tests and I'm pretty sure they have it right. Maybe it is just reporting a misleading error description. Otherwise you should report it to Autobahn.

**Comment by jimmyt857** [comment]
Ok. I've passed all the tests now, although there are still a few cases where it doesn't close the connection the way autobahn wants. Just curious, do you have any ideas on when you want to integrate this into the master branch?

**Comment by alexhultman** [comment]
Sorry for the delay, I forgot this thread. I'm thinking about doing a major refactoring to structure things up some more. Client support should probably be added in the same go as the refactoring, or after it at least. If you get things working passing all of autobahn I could take a look at it. You could join the gitter chat so that we can discuss how the refactor could be done etc.

**Comment by jimmyt857** [comment]
Ok. I haven't been able to figure out what goes wrong in these tests yet. It seems like the autobahn server disconnects instead of sending the close message (recv returns 0/-1) and so the client isn't able to send the final close.
