### ISSUE TITLE
Node: why target the WS interface?

### ISSUE THREAD

**Issue by ronkorving** [alexhultman/uWebSockets#29]
I understand `ws` is popular, but I see opportunity to improve on the WS API here. Why stick to it rigorously?

**Comment by alexhultman** [comment]
Well from my experience with node-lws I learnt Node devs cannot handle an effective C-like interface. I got maybe 5 bug reports about "hangs and crashes" in the lib, when those crashes was caused by invalid usage. Besides, whatever interface you pick will still be significantly slower than native, as you can see in the benchmarks of node-lws. You lose at least 30% perf by going from native to JS and back. So this time I want to target something familiar and idiot proof.

**Comment by alexhultman** [comment]
But it is also about reaching out. Performance interested Node devs are going to be using ws, since that is "the fastest" WebSocket lib for Node.js. So by targeting that interface I can reach out to a large amount of devs and they only need to change require('ws') with require ('uws') and boom - now their server runs on a fraction of the memory. Also - if it turns out they need to swap back they can easily do so. If I have a different interface the swap would need to be flawless, which I know it wont be.

**Comment by ronkorving** [comment]
I think most of the people who want that kind of swappability will use Primus on top of a WebSocket library anyway. I understand that a C-ish API is also not a good thing (I'm not advocating for that), but this is an opportunity to correct any mistakes that may exist in the `ws` API. I wouldn't throw away that opportunity by-design.

**Comment by alexhultman** [comment]
What mistakes in ws are you thinking of? That interface is pretty simple - ofc the fact that every connection registers its own events using strings are pure performance suicide and full blown insanity but people seem to be fine with that.

**Comment by ronkorving** [comment]
Well, for one, it's impossible to tell how much a connection's buffer is filled up with ws, something Node streams for example solve. Backpressure awareness would be nice to have.

**Comment by alexhultman** [comment]
Well ofc I can *extend* the ws interface. The point is that the *base* should be compatible with what most people are already using. You could easily add extra functions for these specific things.
