### ISSUE TITLE
Handle upgrades immediately

### ISSUE THREAD

**Issue by lpinca** [alexhultman/uWebSockets#45]
If i'm not mistaken this [code](https://github.com/alexhultman/uWebSockets/blob/be881cee50262d73a4d89d28c4754264edc0a19b/nodejs/dist/uws.js#L112-L125) is synchronous.

I wonder if it is feasible to change that method to make it return `nativeSocket` directly, so instead of registering a new connection handler every time we will simply have something like this:

```js
const socket = server.upgrade(fd, header);
```

which is similar to the API used by [`faye-websocket-node`](https://github.com/faye/faye-websocket-node).

In the `ws` interface we can then warp it in the `handleUpgrade(req, socket, head, cb)` method.

**Comment by alexhultman** [comment]
upgrade is always serial when called from JS-land, but can be serial or async when called from C++ (you pass a boolean to specify that). I could make upgrade directly return the nativeSocket but that would make the native C++ interface differ from the "native" JS interface. Also, I would have to do kind of the same logic only in C++, so the problem would only move from JS to C++. I want the two interfaces to be 1:1 as far as possible, and then do any needed modifications in JS land.

If you know that you can improve memory usage by not setting a closure all the time, maybe you would get the same memory improvements by only setting the `function` once, but having a "global" variable pass along the data? I'm not sure.

**Comment by lpinca** [comment]
You mean something like this right?
```js
let request = null;

wss.onConnection(function (socket) {
  // do stuff with `request`
  request = null;
});

server.on('upgrade', function (req, socket, head) {
  request = req;
  wss.upgrade(socket._handle.fd, req.headers['sec-websocket-key']);
  socket.destroy();
});
```
I'm not very happy with it.
Returning the request object with the socket passed to `onConnection` or as an additional argument is also not feasible I guess as it is pretty heavy.

**Comment by alexhultman** [comment]
Pretty much yes, but you see the problem - if I make upgrade return a socket, I still need to do exactly the same logic, but "hidden" in C++. This was the way I did it in node-lws, in reality the exact same thing happened under the hood. This time I do not want to build a very complex wrapper, it should just be minimal and to the point and as long as you can take the building blocks and build a tower it has served its purpose. Especially since this interface is not even officially exposed, the exposed interface is the ws one.

**Comment by lpinca** [comment]
Yes I understand and it makes sense.
I just find it odd to add a callback when that callback is called in same tick, but I can live with it.

**Comment by alexhultman** [comment]
In node-lws I tried to do everything in the wrapper and I ended up with many different paths the code could take, like if I a socket was closed by the code, or by the network that had two paths: the callback in case of the network close and not the callback in terms of the from-function-call triggered close. Same with connection and upgrade. This time I want to have only one path for every event and just change the callback when that is needed. It makes things look a little weird but the underlying code becomes simple. This interface will change with time but I do not want to change it just because, if there are other reasons I can change it.
