### ISSUE TITLE
Setup prebuild

### ISSUE THREAD

**Issue by corbinu** [alexhultman/uWebSockets#54]
First of all love the repo always looking for better performance. To speed up installs and easy the barrier to use I was wondering if you had considered using https://www.npmjs.com/package/prebuild

Which compiles binaries on a CI and then uploads them to github.

I would be happy to do a PR for travis-ci for Linux and OS X and appveyor for Windows

**Comment by alexhultman** [comment]
Hi, I have heard things about Travis and I did some testing but I was not very satisfied with the old version of Ubuntu (or Ubuntu at all, really). But I guess that doesn't matter. Currently I build things manually so I would appreciate any help on getting a working Travis set-up. Could you try and fork the repo and test on your fork so that we don't end up with 6 test commits?

**Comment by corbinu** [comment]
Sure no problem I can just test the fork under an npm scoped package did you want me to setup appveyor also?

**Comment by alexhultman** [comment]
I don't know what appveyor is? Seems like Travis for Windows? In that case, sure if you can get the addon to build on Windows that would be pretty neat.

**Comment by corbinu** [comment]
Yes exactly... travis can build Linux and Mac packages... Appveyor builds Windows

**Comment by alexhultman** [comment]
@corbinu How are things going?

**Comment by corbinu** [comment]
@alexhultman Should be able to get this one by Wednesday evening got sidetracked with "work work"

**Comment by alexhultman** [comment]
@corbinu I've improved the Makefile I use. It is now able to download the Node.js SDKs and build the binaries without any other dependencies. I guess there is no persistent storage in Travis so it would need to download everything each time which is very inefficient but I guess that's how everyone is doing things.

1. clone the repo
2. cd uWebSockets/nodejs
3. make targets (this downloads the Node.js headers for all targets)
4. make (this ofc builds the binaries in dist)

Then I guess it should commit the binaries and push to GitHub.

**Comment by alexhultman** [comment]
Is Travis for real? They are using Ubuntu version from before I was born. Their C++ support is not even up to C++11, I mean the internet was not even invented before 2011. This service is just pure bullshit, seriously.

**Comment by alexhultman** [comment]
I have set up Travis for OS X. They have very recent and good OS X support but I got a hemorrhage from their stone aged Linux support. What is needed now is some way of retrieving the built binaries.

**Comment by corbinu** [comment]
@alexhultman Sorry for all the delays was working on fixing a bug in prebuild. As for Travis yes they have a very old version but you can tell it to use trusty. Or just sent up your own docker container however you like and build in that.

As for saving the artifacts. It is up to you. For node I use "prebuild" which adds them to github releases. That or travis can save them to an S3 bucket. I can set up either one based on what you have done tomorrow. Just let me know what you would rather. 

For an example of how to use the newer Ubuntu with travis (actually and docker and OS X and saving to github releases) this is what I currently do

https://github.com/corbinu/couchnode/blob/master/.travis.yml

I was fixing a bug yesterday for Linux binaries for Alpine linux(doesn't use gnu libc) in prebuild but probably best to wait to use that here until it is merged in

**Comment by corbinu** [comment]
@alexhultman Would you be open to moving the node project to a separate repo. It seems travis can only do one type of deploy per repo. So if you want the node project deployed to npm then it can't also deploy the c binaries to this Github releases (however if you want to just make the C users built it themselves then that is not an issue.

**Comment by alexhultman** [comment]
I only plan on prebuilding for Node.js, later I'll add the project to homebrew etc. I dont want every push to publish to NPM, I'm thinking it would probably be best to just have Travis commit the binaries and have me manually publish to NPM.

**Comment by corbinu** [comment]
@alexhultman ok I can set that up. I just have Travis setup to push NPM on tags and then I just tag the release versions(git-flow) but I will do the PR a little later without npm for now

**Comment by corbinu** [comment]
@alexhultman Apparently I should have taken a closer look at the make file. I don't believe prebuild works if your not using node-gyp or node-ninja to build the module's C++ deps but I will take a closer look at the docs

**Comment by corbinu** [comment]
@alexhultman Another quick note what versions of Node were you planning to support. I don't see a min version in the package.json however I can tell from the JS that it will only run on +4 do you want me to rewrite it as ES5 or I can setup a transpiler like Babel. Or better yet I can setup two versions one ES5 with the current callbacks and another ES6 with Babel that supports promises.

**Comment by alexhultman** [comment]
This project is Node.js 4+ only. I didn't want to use node-gyp since it is basically yet another build system (the millionth one). Instead I simply use the standard Unix make. If you need to, you can create a binding.gyp but the main issue remaining would be to get the binaries committed or something so that I can get something valuable out of Travis.

**Comment by corbinu** [comment]
@alexhultman Ok that simplifies things. How as for node-gyp the issue is going to be that if it isn't used then there is nothing for prebuild to fallback to to build the binaries if they are not available (for example installing the node module on Windows/SmartOS/BSD/Alpine etc currently succeeds in the npm install but then fails on startup due to no binary being available. I am setting up a new makefile and binding.gyp in my fork so you can take a look

**Comment by corbinu** [comment]
@alexhultman Does that make sense if I just set it up. Don't want to burn a bunch of time on it if your not wanting to use node-gyp

**Comment by kapouer** [comment]
Hello,
may i up that suggestion by insisting on the fact nearly if not all nodejs addons use node-gyp to compile - and nodejs users expect their usual binding.gyp, so that `npm install uws` actually compiles the addon, not install an untrustable binary.
For the "install untrusted binary first" and "fallback to build" thing, there is also node-pre-gyp.
Side note: did you notice the existence of https://github.com/nodejs/nan ? It helps a lot with v8 api changes over time.

**Comment by alexhultman** [comment]
This is kind of controversial - some [JS] developers are 100% fanatical purists that refuse anything node-gyp simply because, yeah, I don't know why. I want to make things as seamless as possible by providing pre-built binaries that just work out of the box.

Trusting a binary is not really that hard - consider the binary a checksum of its source code. If you want to validate it you can compare your compiler output with mine. Remember that Node.js is distributed in binary form, just like about every piece of software out there.

I know of NaN but I don't like it, I rather use vanilla V8 for a number of reasons. But yeah, I have considered using node-gyp but this depends on how it is received by devs - I know a lot of them will be discouraged if they need to set up a compiler (even if this is a single one-liner in any Unix).

**Comment by corbinu** [comment]
@Alexhultman not having to setup a compiler is what prebuild is for I am suggesting I would setup node-gyp so those on strange systems(SmartOS) or wanting to build their own bianary can. But then upload a prebuilt binary for Linux, Windows and OS X. The prebuild module depends on node-gyp however so just need to know your ok with using it

https://www.npmjs.com/package/prebuild

**Comment by alexhultman** [comment]
My current flow is:

* Write code on Linux
* Compile on OS X & Linux (using the Makefile)
* NPM publish the 6 binaries (Node.js 4, 5, 6)

What I need, or maybe not need but would appreciate, is modifications to the .travis.yml so that the OS X binaries built are sent to me somehow, preferably committed to GitHub (if that does not come with obvious security issues). If you need to add a binding.gyp then that's fine as long as you can set the same flags (I know node-gyp adds a bunch of bullshit flags like -fno-exceptions etc). I use exceptions.

**Comment by kapouer** [comment]
@alexhultman doing a PR with a binding.gyp. "fixing" the npm package is another matter.

**Comment by alexhultman** [comment]
Implying the package is broken is maybe a little harsh. As far as I know `npm install uws` currently works and provides a working module out of the box.

**Comment by corbinu** [comment]
I am not sure about flags in node-gyp maybe is better if somebody else takes this is just getting way more complicated then I first expected

**Comment by kapouer** [comment]
Sorry for the harsh part. I meant broken w.r.t. being able to build from the npm package, as it is customary to be able to. That's PR #85.
