### ISSUE TITLE
support client verification before socket opens

### ISSUE THREAD

**Issue by shaharmor** [alexhultman/uWebSockets#60]
Hi,

Will it be possible to support client verification like the `ws` module's `verifyClient` option? https://github.com/websockets/ws/blob/master/doc/ws.md#optionsverifyclient

**Comment by alexhultman** [comment]
Hi,

This depends on demand. The first goal is to have a minimal implementation which covers about 80% of all use cases, enough to get the module to replace ws in socket.io and such projects like primus, SC, etc. Any ws-specific features that are rarely used will be skipped to begin with.

**Comment by FlorianBELLAZOUZ** [comment]
+1

**Comment by jondubois** [comment]
SocketCluster uses the```verifyClient``` feature of the WS module.
Is there a clean way to block/accept WebSocket connection attempts without using verifyClient? If there is, maybe that's something we could implement on our end.

I guess we could block the HTTP ugrade request ourselves - Is this a good idea or is it cleaner if uWS handles this?

**Comment by alexhultman** [comment]
To be honest I have no idea what verifyClient is since it is not really part of what makes a minimal WebSocket server. You should be able to implement whatever authorization you need ontop of the current interface. You can decide to pass or block any connection by using the handleUpgrade accordingly. If this feature is easy to add and very well used then I could consider it. Is this kind of functionality integrated into other WebSocket servers?

**Comment by jondubois** [comment]
I looked into it a bit more.
Because I'm passing the http server as a 'server' option when creating the uWS Server, uWS will listen to the 'upgrade' event on the server (https://github.com/alexhultman/uWebSockets/blob/master/nodejs/dist/uws.js#L121) - Because of this I cannot block the request before it reaches the uWS server... The verifyClient handler allows you to add middleware from outside even though the HTTP server is being handled internally by the WS server.

It looks like it's not much code to implement: https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L315-L335

Maybe it's just a matter of calling the verifyClient handler here somewhere: https://github.com/alexhultman/uWebSockets/blob/master/nodejs/dist/uws.js#L121-L130
... and then aborting the connection if it doesn't pass.

It looks like verifyClient works either synchronously (return) or asynchronously (with callback).

**Comment by alexhultman** [comment]
It does seem very simple yes. If you want you could send a pull request.

**Comment by alexhultman** [comment]
1797dd3986829cc10aa9420bcafc726b53a4eda0

This needs some fixes but should work, right?

**Comment by alexhultman** [comment]
There is basic support in v0.2.5. It ignores HTTP code and message but otherwise it works.

**Comment by shaharmor** [comment]
The async callback wont work as needed. It should only upgrade the request
if the callback passes

**Comment by alexhultman** [comment]
I did 3 commits where it was broken for the first 2. Could you check the final source? In my testing all 4 cases (pass, block, pass callback, block callback) worked.

**Comment by shaharmor** [comment]
If the callback is really async (as in nexttick) it won't work correctly

**Comment by alexhultman** [comment]
It should work now, right?
