### ISSUE TITLE
Publish version for node 6

### ISSUE THREAD

**Issue by lpinca** [alexhultman/uWebSockets#79]
This is not an issue, just a reminder.
Right now there is no build for node 6. An error is thrown when using uws with node 6.

**Comment by alexhultman** [comment]
I don't know how I'm going to support different Node.js versions. LTS + Current should be enough for most users. NPM is completely moronic since it downloads all files all the time. I need it to download only the files for you particular system and Node.js version. They claim this is already solved with various npm modules but they look like pure crap and I do not want to add stuff to fix fundamental flaws in NPM. They should just have different folders for different systems + Node.js versions.

4.x + 6.x

**Comment by lpinca** [comment]
> LTS + Current should be enough for most users.

I mostly agree with this, but you'll cut out all the users who don't want or can't update node.

**Comment by alexhultman** [comment]
What if you have a minimal shim on NPM that, on require, checks what version it has downloaded (if any) and downloads the files it needs if the version doesn't match the one in the package.json?

**Comment by alexhultman** [comment]
Anyways, that would be a future solution. I'll just go for 4, 5, 6 - that will add about 100 kb of download for now. Maybe its better to have a sliding range of the three latest versions.

**Comment by alexhultman** [comment]
It compiled fine, no breaking changes.

**Comment by alexhultman** [comment]
v0.2.9 has 4, 5, 6 support :+1:

**Comment by lpinca** [comment]
Great, everything should be ok now until october 2016.

**Comment by alexhultman** [comment]
What happens then? Node.js 7? Well, I cannot make plans longer than 3 days so that's fine with me :)

**Comment by lpinca** [comment]
haha, yeah node 6 will be marked as LTS and node 7 as current.

**Comment by alexhultman** [comment]
I forgot about compression - NPM is probably storing the modules as tarballs with compression. If I compress the dist folder it becomes about 160 kb in total. So the size is still okay :+1:
